### ISSUE TITLE
Multiple inserts

### ISSUE THREAD

**Issue by khepin** [krisajenkins/yesql#74]
I can't find any reference to it in the doc, but is there a way to do multiple inserts such as:

```sql
INSERT INTO `messages` (`message`, `timestamp`)
VALUES
    ('hello', UNIX_TIMESTAMP(NOW())),
    ('hi there', UNIX_TIMESTAMP(NOW())),
    ('message 3', UNIX_TIMESTAMP(NOW()));
```

Where the number of elements to insert can vary from one time to the next.

**Comment by mshenfield** [comment]
@khepin check out the conversation on issue #51 (support for batch inserts).

**Comment by khepin** [comment]
Awesome! Thanks.
